### ISSUE TITLE
Cura 5.7.0: Plugin could not be loaded

### ISSUE THREAD

**Issue by NuclearPhoenixx** [jellespijker/elevated_beats_n_slices#15]
Hi there,

for some reason the plugin does not work anymore for me in Cura 5.7.0. On startup it just states the following:

![msg](https://github.com/jellespijker/elevated_beats_n_slices/assets/17517687/c645fcde-ea6e-4242-8eae-1f97a772a6f8)

No idea if that's a problem specific to my Cura install or something with the plugin unfortunately 😕 
I know this is a really bare issue with not much info, but I have no idea where to grab some logs as it doesn't even mention anything like that. It just throws the error at me.

**Comment by StrandedSoftwareDeveloper** [comment]
I'm having the same error and I found this in stderr.log:
```[35m2024-04-20 02:20:50,937[0m - [31mERROR[0m - [37m[MainThread] UM.PluginRegistry._findPlugin [795]: Exception: Import error loading module ElevatedBeatsnSlices[0m
[35m2024-04-20 02:20:50,939[0m - [31mERROR[0m - [37m[MainThread] UM.PluginRegistry._findPlugin [795]: Traceback (most recent call last):[0m
[35m2024-04-20 02:20:50,939[0m - [31mERROR[0m - [37m[MainThread] UM.PluginRegistry._findPlugin [795]:   File "UM/PluginRegistry.py", line 793, in _findPlugin[0m
[35m2024-04-20 02:20:50,939[0m - [31mERROR[0m - [37m[MainThread] UM.PluginRegistry._findPlugin [795]:     spec.loader.exec_module(module)[0m
[35m2024-04-20 02:20:50,940[0m - [31mERROR[0m - [37m[MainThread] UM.PluginRegistry._findPlugin [795]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module[0m
[35m2024-04-20 02:20:50,940[0m - [31mERROR[0m - [37m[MainThread] UM.PluginRegistry._findPlugin [795]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed[0m
[35m2024-04-20 02:20:50,940[0m - [31mERROR[0m - [37m[MainThread] UM.PluginRegistry._findPlugin [795]:   File "/home/ssd/.local/share/cura/5.7/plugins/ElevatedBeatsnSlices/ElevatedBeatsnSlices/__init__.py", line 7, in <module>[0m
[35m2024-04-20 02:20:50,941[0m - [31mERROR[0m - [37m[MainThread] UM.PluginRegistry._findPlugin [795]:     from . import ElevatedBeatsNSlicesPlugin[0m
[35m2024-04-20 02:20:50,941[0m - [31mERROR[0m - [37m[MainThread] UM.PluginRegistry._findPlugin [795]:   File "/home/ssd/.local/share/cura/5.7/plugins/ElevatedBeatsnSlices/ElevatedBeatsnSlices/ElevatedBeatsNSlicesPlugin.py", line 11, in <module>[0m
[35m2024-04-20 02:20:50,941[0m - [31mERROR[0m - [37m[MainThread] UM.PluginRegistry._findPlugin [795]:     from PyQt6.QtMultimedia import QAudioOutput, QMediaPlayer[0m
[35m2024-04-20 02:20:50,942[0m - [31mERROR[0m - [37m[MainThread] UM.PluginRegistry._findPlugin [795]: ModuleNotFoundError: No module named 'PyQt6.QtMultimedia'[0m
[35m2024-04-20 02:20:50,942[0m - [33mWARNING[0m - [37m[MainThread] UM.PluginRegistry._populateMetaData [892]: Could not find plugin ElevatedBeatsnSlices[0m
```
I tried installing python3-pyqt6-multimedia, but the error didn't change. I'm using the AppImage version of Cura on Void Linux if that's relevant.

**Comment by jellespijker** [comment]
thx, I will put in on the backlog,  this probably happens because  PyQt6 used by Cura 5.7.x has been upgraded.

I'm unfortunately rather busy atm, so it might take a while before I get to it. If someone in the community feels up to taking a look and opening a PR you would make me very happy

**Comment by Kataklysim** [comment]
![2024-11-25_12h34_07](https://github.com/user-attachments/assets/b48949df-21ac-41e3-af66-471f36d18124)
Running Cura 5.9 Have uninstalled several times with same result. 
Please fix?

**Comment by NuclearPhoenixx** [comment]
Just had a look at the log, and this is what Cura 5.9 reports:

```
2024-12-05 13:15:51,174 - INFO - [MainThread] UM.PluginRegistry.loadPlugin [540]: Loaded plugin CalibrationShapes 2.2.4
2024-12-05 13:15:51,179 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]: Exception: Import error loading module ElevatedBeatsnSlices
2024-12-05 13:15:51,180 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]: Traceback (most recent call last):
2024-12-05 13:15:51,181 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:   File "UM\PluginRegistry.py", line 793, in _findPlugin
2024-12-05 13:15:51,181 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:     spec.loader.exec_module(module)
2024-12-05 13:15:51,181 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-12-05 13:15:51,182 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-12-05 13:15:51,182 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:   File "C:\Users\Matthias\AppData\Roaming\cura\5.9\plugins\ElevatedBeatsnSlices\ElevatedBeatsnSlices\__init__.py", line 7, in <module>
2024-12-05 13:15:51,182 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:     from . import ElevatedBeatsNSlicesPlugin
2024-12-05 13:15:51,182 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:   File "C:\Users\Matthias\AppData\Roaming\cura\5.9\plugins\ElevatedBeatsnSlices\ElevatedBeatsnSlices\ElevatedBeatsNSlicesPlugin.py", line 11, in <module>
2024-12-05 13:15:51,183 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:     from PyQt6.QtMultimedia import QAudioOutput, QMediaPlayer
2024-12-05 13:15:51,183 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]: ModuleNotFoundError: No module named 'PyQt6.QtMultimedia'
2024-12-05 13:15:51,183 - WARNING - [MainThread] UM.PluginRegistry._populateMetaData [892]: Could not find plugin ElevatedBeatsnSlices
2024-12-05 13:15:51,186 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]: Exception: Import error loading module ElevatedBeatsnSlices
2024-12-05 13:15:51,186 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]: Traceback (most recent call last):
2024-12-05 13:15:51,187 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:   File "UM\PluginRegistry.py", line 793, in _findPlugin
2024-12-05 13:15:51,187 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:     spec.loader.exec_module(module)
2024-12-05 13:15:51,187 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-12-05 13:15:51,187 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-12-05 13:15:51,188 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:   File "C:\Users\Matthias\AppData\Roaming\cura\5.9\plugins\ElevatedBeatsnSlices\ElevatedBeatsnSlices\__init__.py", line 7, in <module>
2024-12-05 13:15:51,188 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:     from . import ElevatedBeatsNSlicesPlugin
2024-12-05 13:15:51,188 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:   File "C:\Users\Matthias\AppData\Roaming\cura\5.9\plugins\ElevatedBeatsnSlices\ElevatedBeatsnSlices\ElevatedBeatsNSlicesPlugin.py", line 11, in <module>
2024-12-05 13:15:51,189 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]:     from PyQt6.QtMultimedia import QAudioOutput, QMediaPlayer
2024-12-05 13:15:51,189 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [795]: ModuleNotFoundError: No module named 'PyQt6.QtMultimedia'
2024-12-05 13:15:51,190 - ERROR - [MainThread] UM.PluginRegistry.removeCorruptedPluginMessage [577]: Exception: Error loading plugin ElevatedBeatsnSlices:
2024-12-05 13:15:51,191 - ERROR - [MainThread] UM.PluginRegistry.removeCorruptedPluginMessage [577]: NoneType: None
```

Clearly `PyQt6.QtMultimedia` is missing. No idea if Cura stopped shipping that or if the plugin should be shipping with that dependency. Unfortunately, I have no idea about cura plugin development, so I won't be of any further help than that 😕

**Comment by jellespijker** [comment]
Cura has no need for QtMultimedia if anything it should be part of this plugin.
I'm however swamped for time at the moment so it isn't likely that I have the time to work on this issue, and the plugin was intended as more of a joke to mess with my colleagues.

PR's are welcome and if you tag me I can make sure that they are reviewed and a new plugin will be published
